from PyQt4.QtGui import QApplication

Connect = QApplication.translate("dev_client", "Connect")

NoConn = QApplication.translate("dev_client", "There aren't connections defined")

ConnError= QApplication.translate("dev_client", "Unable to establish connection")

CloseConfirm = QApplication.translate("dev_client", "Really quit?")

CloseConn = QApplication.translate("dev_client", "Really close connection?")

FatalError = QApplication.translate("dev_client", "Fatal Error, please restart your client")

ConnLost = QApplication.translate("dev_client", "Connection lost")

NotConnected = QApplication.translate("dev_client", "Client is not connected")

UpdateFail = QApplication.translate("dev_client", "Unable to download updates")