from PyQt4.QtGui import QApplication

Connect = QApplication.translate("dev_client", "Connect", None, QApplication.UnicodeUTF8)

NoConn = QApplication.translate("dev_client", "There aren't connections defined", None, QApplication.UnicodeUTF8)

ConnError= QApplication.translate("dev_client", "Unable to establish connection", None, QApplication.UnicodeUTF8)

CloseConfirm = QApplication.translate("dev_client", "Really quit?", None, QApplication.UnicodeUTF8)

CloseConn = QApplication.translate("dev_client", "Really close connection?", None, QApplication.UnicodeUTF8)

FatalError = QApplication.translate("dev_client", "Fatal Error, please restart your client", None, QApplication.UnicodeUTF8)

ConnLost = QApplication.translate("dev_client", "Connection lost", None, QApplication.UnicodeUTF8)

NotConnected = QApplication.translate("dev_client", "Client is not connected", None, QApplication.UnicodeUTF8)

UpdateFail = QApplication.translate("dev_client", "Unable to download updates", None, QApplication.UnicodeUTF8)