from PyQt4.QtGui import QApplication

ReqFields = QApplication.translate("option", "The following fields are required")
Command = QApplication.translate("option", "Command")

Name = QApplication.translate("option", "Name")
Host = QApplication.translate("option", "Host")
Port = QApplication.translate("option", "Port")
Connection = QApplication.translate("option", "Connection")
UniqueName = QApplication.translate("option", "Connection name must be unique")
ConfirmDelete = QApplication.translate("option", "Are you sure to delete the connection?")

NewMacro = QApplication.translate("option", "Create New","macro")
Macro = QApplication.translate("option", "Macro")
Keys = QApplication.translate("option", "Keys")
UniqueKeys = QApplication.translate("option", "Key sequence must be unique")
ShortcutKeys = QApplication.translate("option", "Key sequence must be different from all the shortcut keys")

Accounts = QApplication.translate("option", "Accounts")
BadPrompt = QApplication.translate("option", "Bad format on prompt")

NewAlias = QApplication.translate("option", "Create New", "alias")
Alias = QApplication.translate("option", "Alias")
Label = QApplication.translate("option", "Label")
Body = QApplication.translate("option", "Body")
UniqueLabel = QApplication.translate("option", "The label must be unique")

NewTrigger = QApplication.translate("option", "Create New", "trigger")
Trigger = QApplication.translate("option", "Trigger")
Pattern = QApplication.translate("option", "Pattern")
UniquePattern = QApplication.translate("option", "The pattern must be unique")
ReqColors = QApplication.translate("option", "At least one between text and background color is required")

NoKeypad = QApplication.translate("option", "The keypad controls are not available on your O.S. due to a limitation of the underlying platform.")
